Repository PubMatic/OpenWrap, pull requests merged in 2021-03, with the labels that each got.

#225 Price Granularity and Granular Multiplier Support
  src_new/adapters/prebid.js
  src_new/config.js
  src_new/constants.js
  test/config.spec.js
Labels: needs review

#248 Removed src attribute while creating iFrame
  src_new/util.js
Labels: ready to merge

#247 Use addAdunits
  src_new/adapters/prebid.js
Labels: merged, ready to merge

#249 Added id field along with siteId for ix
  src_new/adapters/prebid.js
Labels: ready to merge

#254 changes for outstreamplayer not defined
  src_new/util.js
Labels: needs review

#246 Feature/abtest
  src_new/config.js
  src_new/constants.js
  test/config.spec.js
Labels: needs review

#251 OpenWrap Stable v22.0.0
  build.sh
  gulpfile.js
  init-build.sh
  package.json
  src_new/adapterManager.js
  src_new/adapters/prebid.js
  src_new/bid.js
  src_new/bidManager.js
  src_new/conf.js
  src_new/config.js
  src_new/constants.js
  src_new/controllers/custom.js
  src_new/controllers/gpt.js
  src_new/controllers/idhub.js
  src_new/controllers/uas.js
  src_new/owt.js
  src_new/util.js
  test/adapterEntry.spec.js
  test/adapterManager.spec.js
  test/adapters/prebid.spec.js
  test/bid.spec.js
  test/bidManager.spec.js
  test/bmEntry.spec.js
  test/config.spec.js
  test/controllers/custom.spec.js
  test/controllers/gpt.spec.js
  test/controllers/idhub.spec.js
  test/controllers/uas.spec.js
  test/gdpr.spec.js
  test/globals.js
  test/slot.spec.js
  test/util.spec.js
  webpack.config.js
Labels: ready to merge
